# Generated by Django 3.1.7 on 2021-09-21 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.PositiveIntegerField()),
                ('tipos', models.CharField(choices=[('Horas', 'Horas'), ('Mensual', 'Mensual'), ('Nocturno', 'Nocturno')], max_length=10)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehiculo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=50)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.persona')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.tipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('subtotal', models.PositiveIntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.factura')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.servicio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.vehiculo')),
            ],
        ),
    ]
